iron:
  token: "t"
  project_id: "p"

# Queue to pull messages off
workqueue: myqueue
# Queue to set alerts on
workqueue_alertqueue: myqueue_alerts
# Name of worker to start processing workqueue
worker: consumer

